Fix bug with compromised tests
Invictum/serenity-reportportal-integration pull request #144
Opened 2021-10-21 11:36 UTC by v1-wizard

We found that compromised tests could be executed by JUnit twice and duplicated in the Report Portal. This fix should help with this.

Before:
![2021-10-21_14-29](https://user-images.githubusercontent.com/5778094/138269091-3b29f303-f42a-4825-bb9a-19df45cdb4df.png)
After:
![2021-10-21_14-28](https://user-images.githubusercontent.com/5778094/138269122-be984c56-7e3c-41d2-9aa7-c924dae3711a.png)

2021-11-01 14:08 UTC, v1-wizard commented
@Invictum hi. How are you? Any updates? =)

2021-11-16 09:47 UTC, v1-wizard commented
@Invictum any updates?

2021-12-16 13:20 UTC, v1-wizard commented
@Invictum Hey, how are you?

2022-01-10 11:29 UTC, v1-wizard commented
@Invictum Are you still here?

2022-06-01 09:01 UTC, v1-wizard commented
Hi @Invictum. How are you?

2023-08-25 13:42 UTC, v1-wizard commented
Hi @Invictum and @grey-rain could you merge my PR. This would help us to remove our internal version and start updating version of integration. Thanks.

2023-09-16 18:45 UTC, grey-rain commented on src/main/java/com/github/invictum/reportportal/recorder/Regular.java
> +    final int RETRIES_COUNT = ReportIntegrationConfig.get().retriesCount();
as it is not a constant anymore, please rename it to camelCase.

2023-09-16 19:28 UTC, grey-rain requested changes
https://github.com/Invictum/serenity-reportportal-integration/pull/144/files#r1327996388

2023-09-19 16:16 UTC, grey-rain commented on src/main/java/com/github/invictum/reportportal/recorder/Regular.java
> +    final int RETRIES_COUNT = ReportIntegrationConfig.get().retriesCount();
@v1-wizard

2024-07-29 01:38 UTC, grey-rain commented
Closed as abandoned.

2024-07-29 01:38 UTC, closed without merging